---
title: "나이와 월급의 관계"
author: 정현진
date: July 30, 2020
output: github_document
---
```{r, include=F}
Sys.setenv("LANGUAGE"="EN")
library(foreign)             # SPSS 파일 로드 
library(dplyr)               # 전처리
library(ggplot2)             # 시각화
library(readxl)              # 엑셀 파일 불러오기

#데이터 불러오기
raw_welfare <- read.spss(file = "koweps_hpc10_2015_beta1.sav", to.data.frame = T)

#복사본 만들고 변수 이름 바꿔주기
welfare <- raw_welfare
welfare <- rename(welfare,
                  sex = h10_g3,
                  birth = h10_g4,
                  marriage = h10_g10,
                  religion = h10_g11,
                  income = p1002_8aq1,
                  code_job = h10_eco9,
                  code_region = h10_reg7)
```

## 3. 나이와 월급의 관계
나이 변수를 검토하고 전처리, 월급 변수는 생략 후 변수간 관계 분석

### 분석 절차
변수 검토 및 전처리(나이, 월급) -> 변수간 관계 분석(나이에 따른 월급 평균표 만들기, 그래프 만들기)

#### 1. 변수 검토하기
나이와 월급의 관계를 분석하려면 나이 변수가 필요한데 없다.
년도 변수를 이용해 검토한 후 나이 변수 만들기

```{r,eval=T}
class(welfare$birth)
summary(welfare$birth)
qplot(welfare$ birth)
```


#### 2. 전처리


```{r, eval=T} 
summary(welfare$birth) #이상치 확인
table(is.na(welfare$birth)) #결측치확인
#이상치 결측 처리
welfare$birth <- ifelse(welfare$birth == 9999, NA, welfare$birth)
table(is.na(welfare$birth))
```
-> 이상치와 결측치 없음 

#### 3. 파생변수 만들기 - 나이
2015년에 조사가 진행, 2015년-태어난 년도+1 = 나이

```{r, eval=T} 
welfare$age <- 2015 - welfare$birth +1
summary(welfare$age)
qplot(welfare$age)
```

### 나이와 월급의 관계 분석하기


#### 1. 나이에 따른 월급 평균표 만들기
```{r, eval=T} 
age_income <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(age) %>% 
  summarise(mean_income = mean(income))
head(age_income)
```
#### 2. 그래프 만들기

```{r, eval= T} 
ggplot(data = age_income, aes(x = age, y = mean_income)) + geom_line()
```